### ISSUE TITLE
error on running the app

### ISSUE THREAD

**Issue by outranker** [gwesseling/tesla-app#1]
hi!
congrats on building such a nice looking app

however, i am facing a difficulty getting this app up and running.
the error message is:
```
iOS Bundling failed 71ms
Unable to resolve "./Model" from "src/components/Renderer.tsx"
```

this is what i did to run the app
1. cloned the repo and cd into the tesla-app directory
2. installed packages with `yarn`
3. started the app with `yarn start`

the laptop is mac m1 and i am encountering the issue on both ios simulator (iphone 13) and real device galaxy s20

**Comment by gwesseling** [comment]
Hey Outranker, 

Thanks for making an issue. Since the app was created using a Windows machine file capitalisation does not matter. Therefore one import appeared to be wrong. Should be fixed, if you pull the latest version of the repo.

Have a good day!
