### ISSUE TITLE
Entity not authorized:

### ISSUE THREAD

**Issue by numannaqvi** [gwesseling/tesla-app#6]
When i clone this project and hit command 'npm install' . Its not working and showing this error

[GraphQL] Entity not authorized: AccountEntity[a9889395-64a6-491e-b881-91b544ce2679] (viewer = RegularUserViewerContext[5846debb-1352-4025-bd86-78294d6b7e5d], action = READ, ruleIndex = -1)

**Comment by gwesseling** [comment]
This project is not meant to work out of the box for everyone, it's more to show off what you could do with React Native combined with other packages. It is the responsibility of the person who clones this package to get it working on their environment.

However, that being said, I have made a commit that removes a specific project id from the repository to make it easier for people to get it up and running.
